### ISSUE TITLE
Wild card config incomplete?

### ISSUE THREAD

**Issue by derks** [squash/sudosh2#11]
SudoSH Version: 1.0.6

Having issues with the use case of bootstrapping a node with Chef.  When root's shell is set to sudosh on the remote node, chef-client dies with the following error:

```
chef-client -j /etc/chef/first-boot.json'" isn't allowed to be executed with process or redirect controls.
```

SSH'ing to the node, and running the same above command (still with sudosh as the shell) runs fine.  Here is my `/etc/sudosh.conf`:

```
# Sudosh Configuration File
logdir                  = /var/log/sudosh
default shell           = /bin/bash
delimiter               = -
syslog.priority         = LOG_INFO
syslog.facility         = LOG_LOCAL2
clearenvironment        = yes

# Allow Sudosh to execute -c arguments?  If so, what?
# Obsoleted by permissive option, but left in for backwards compat

-c arg allow = *
```

**Comment by squash** [comment]
[The error you're getting should only be triggered if your command string contains something to redirect output or escape the single-command structure.](https://github.com/squash/sudosh2/blob/master/src/sudosh.c#L192-L199)

 It might be inconsistent to still try to enforce that restriction when wildcards are enabled though. I'll consider that overnight.

**Comment by derks** [comment]
For what it is worth, our use case is that sudosh does not restrict anything, at all, ever.  If that were possible... it would be ideal for us.  We use sudosh strictly for session playback, and not as any sort of security middleware.  In an ideal world (for us), you would never know sudosh was in-between the end-user and the shell.

**Comment by squash** [comment]
I'm convinced that it was inconsistent to disallow those when you're allowing all commands, and have modified the code in commit https://github.com/squash/sudosh2/commit/4a486f75cc1688dee1cbb4d6912a3d4d3dabaccf

Worked good in my testing, I would appreciate it if you can provide feedback after testing before I close this.

**Comment by derks** [comment]
Awesome! Yes, this indeed resolves our issue perfectly (tested).
