### ISSUE TITLE
Multibyte input support

### ISSUE THREAD

**Issue by voron** [squash/sudosh2#15]
sudosh2 seems to not support mulitbyte input locales such as LANG=ru_UA.UTF-8.  How can we fix that?

**Comment by voron** [comment]
What do you think about following quick patch? My ru_UA.UTF-8 input is working fine with it. Does ISTRIP flag is really needed somewhere?
```c
-- sudosh.c.orig	2016-05-28 13:56:35.951239965 +0300
+++ sudosh.c	2016-05-28 13:56:49.296538989 +0300
@@ -640,7 +640,7 @@
     }
 
   termnew.c_cc[VEOF] = 1;
-  termnew.c_iflag = BRKINT | ISTRIP | IXON | IXANY;
+  termnew.c_iflag = BRKINT | IXON | IXANY;
   termnew.c_oflag = 0;
   termnew.c_cflag = termorig.c_cflag;
   termnew.c_lflag &= ~ECHO;
```

**Comment by squash** [comment]
The main issue with trying to add multibyte support is that I can't directly test it. I've started a new tree fr a ground-up rewrite of sudosh in another language that it UTF8 everywhere, but as of yet it's still in its early stages.

With that said, I haven't come up with a great reason to be using ISTRIP. I've got a few other small changes staged up and i'll do a commit this weekend to address this.

**Comment by squash** [comment]
Patch added to HEAD.
