### ISSUE TITLE
Ansible compatibility

### ISSUE THREAD

**Issue by xelgand** [squash/sudosh2#21]
Hello,

I'm trying to use ansible to connect via ssh as a user with sudosh2 as its login shell.

Even the most basic of commands doesn't work.
`ansible <host> -m ping -vvvvvv -c paramiko --user <user>`

If I run the debug mode, ansible is trying to execute this command:

> /bin/sh -c '( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1483951121.44-13816150599912 `" && echo ansible-tmp-1483951121.44-13816150599912="` echo $HOME/.ansible/tmp/ansible-tmp-1483951121.44-13816150599912 `" ) && sleep 0'

As you can guess, the name of the folder it needs to create is unique for every connection, so it's not possible to include the corresponding "-c arg allow" entry in sudosh.conf

Is there any way to allow any command using "-c arg allow"?

**Comment by xelgand** [comment]
I think I found the problem.

In the sudosh.c file, I commented the **// Test for methods of escape** section, recompiled and now the ansible ping command works just fine.

**Comment by roostercactus** [comment]
Hi, with the latest sudosh2 code you can also just do this in the conf file without having to resort to editing the source and compiling.

# What are users allowed to run without an interactive session
-c arg allow = *
