### ISSUE TITLE
Enhancement to ignore lost+found directory during sudosh-replay

### ISSUE THREAD

**Issue by cantlep** [squash/sudosh2#22]
If /var/log/sudosh is on its own filesystem, a lost+found directory is present. When sudosh-replay is run, it throws the following error

[replay.c, line 171]: [warning]: invalid file: lost+found

It doesn't stop anything from working, it looks to be a purely cosmetic error.

Same goes for any directories configured (i.e /var/log/sudosh/host1)

Wondering if this can be fixed.

Thanks
Paul

**Comment by squash** [comment]
fixed by f52296f45e006a23711cb148bed29ed807df8af4
