### ISSUE TITLE
sudosh-replay shows incorrect info

### ISSUE THREAD

**Issue by josueneo** [squash/sudosh2#25]
I just tested the 1.0.6 version and sudosh-replay shows incorrect info, but I don't know if the project is still alive.

## **How to reproduce:**
Adjust the sudosh.conf file to allow any commands with the * wildcard.
`-c arg allow = *`
Then execute:
`sudo sudosh -c "ping 8.8.8.8"`
Then review the output of the sudosh-replay command

## **Actual output**
```
user@host:~> sudo sudosh -c "sudosh-replay"
Date                Duration From         To           ID
====                ======== ====         ==           ==
05/02/2018 21:04:22 -c arg   root         root         ping
05/02/2018 21:04:36 -c arg   root         root         sudosh-replay
```

## **Expected output**
```
user@host:~> sudo sudosh -c "sudosh-replay"
Date                Duration From         To           ID
====                ======== ====         ==           ==
05/02/2018 21:04:22 -c arg   root         root         user-root-1475075700-BUoiTzhStvzBQqzR
05/02/2018 21:04:36 -c arg   root         root         user-root-1475075700-BUoiTzhStvzBQqzR
```

**Comment by squash** [comment]
Hello,

The output is correct. "sudosh -c'" is not intended (or useful) for interactive command execution. It's for allowing commands to be run from remote hosts. Originally to allow things like sftp and scp to work for a user who has sudosh as their login shell. As these are not interactive sessions, the session content is not logged.

sudo should already have a log of commands executed and that log should be used for things like single commands.

**Comment by josueneo** [comment]
Good point, I tought you could be able to watch the output of the -c command.
Thanks!
