### ISSUE TITLE
sudosh always returns SIGCHLD on shell exit

### ISSUE THREAD

**Issue by domdom82** [squash/sudosh2#27]
Not sure if this is a bug or a configuration issue.

I am running sudosh as a login shell for my users. Sudosh in turn spawns bash as the user's actual shell.

When I do ssh into the machine and exit the shell using `logout` the ssh return code is always 17 (SIGCHLD). It should be the sub-shell's return code.

This leads to peculiar behavior of other scripts trying to ssh into the machine and falling back to other machines as they will now always think the ssh command had failed when in fact it didn't.

The code in question is here:

https://github.com/squash/sudosh2/blob/f52296f45e006a23711cb148bed29ed807df8af4/src/sudosh.c#L418-L420

where the `bye` function is registered as a handler for SIGCHLD signals.

In the `bye` function we exit with the signal number:

https://github.com/squash/sudosh2/blob/f52296f45e006a23711cb148bed29ed807df8af4/src/sudosh.c#L680

Why is this needed? Any advice?

**Comment by squash** [comment]
In the case of a sigchild this is likely the wrong behavior, as this is the result of the spawned shell terminating regardless of how it terminates.

**Comment by squash** [comment]
Fixed in aab4a19
