### ISSUE TITLE
Include Hostname in sudosh-replay log list

### ISSUE THREAD

**Issue by refrain** [squash/sudosh2#3]
I know you aren't taking feature requests, but hear me out...

I have a cluster of servers I want to run sudosh on, but sudosh does not report the hostname from which each log was generated without actually playing back the log and looking at the hostname in the command prompt.

It would be great if we could tell at a glance when running sudosh-replay which host generated each log.

**Comment by squash** [comment]
I'll have a look tomorrow and see how hard it will be to add this without breaking compatibility with existing session recordings.

**Comment by squash** [comment]
Sorry for the delay on this. I can't easily add the hostname field without breaking compatibility, that would have to be done in a fork.

I assume you're logging to a network filesystem, the most straightforward suggestion I have would be to add the hostname to the log dir in sudosh.conf.
