### ISSUE TITLE
sudosh2 not working with ssh Agent Forwarding

### ISSUE THREAD

**Issue by none-da** [squash/sudosh2#30]
When using SSH Agent forwarding sudosh2 is not tracking certain ssh actions. Let me explain. Here is my setup:

client => bastion => server

On my client, I am executing 👇
```sh
ssh -A -t nanda@bastion ssh -v ubuntu@server
```
Once I am logged-in to the server I am executing a few commands like 👇
```sh
ubuntu@server:~$ python3
Python 3.8.5 (default, Jul 28 2020, 12:59:40)
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import datetime
>>> datetime.datetime.now()
datetime.datetime(2020, 12, 3, 5, 42, 30, 220312)
>>>
ubuntu@server:~$
```
But when I `sudosh-replay` I see this 👇
```
root@bastion:/var/log/sudosh# sudosh-replay
Date                Duration From         To           ID
====                ======== ====         ==           ==
12/02/2020 23:30:33 22s      nanda        nanda        nanda-nanda-1606932033-iE9aiiyTLKToWafW
12/03/2020 11:12:13 -c arg   nanda        nanda        ssh

Usage: sudosh-replay ID [MULTIPLIER] [MAXWAIT]
See 'sudosh-replay -h' for more help.
Example: sudosh-replay ssh 1 2
root@bastion:/var/log/sudosh#
```
As you can see the second entry is messed up where `Duration` is wrong and `ID` is also not correct. I am not sure if its a problem with `sudosh-replay` or the sudosh which is preparing the `time`, `script`, `interactive` files. Infact in my `/var/log/sudosh` directory, I see only the `interactive` file and no `time` or `script` files 👇. 
```
root@bastion:/var/log/sudosh# ls -ltrh
-rw------- 1 nanda nanda  501 Dec  2 23:30 nanda-nanda-time-1606932033-iE9aiiyTLKToWafW
-rw------- 1 nanda nanda 1.3K Dec  2 23:30 nanda-nanda-script-1606932033-iE9aiiyTLKToWafW
-rw-rw-r-- 1 nanda nanda    4 Dec  3 11:12 nanda-nanda-interactive-1606974133-uO6CZpHFHLq9rafx
-rw-rw-r-- 1 nanda nanda    4 Dec  3 11:15 nanda-nanda-interactive-1606974332-JicmJyoEq1o4eAxk
root@bastion:/var/log/sudosh# cat nanda-nanda-interactive-1606974332-JicmJyoEq1o4eAxk
ssh
root@bastion:/var/log/sudosh#
```
Is this a problem with Agent Forwarding technique ?
 #### sudosh.conf
```
# Sudosh Configuration File
logdir			= /var/log/sudosh
default shell		= /bin/sh
delimiter		= -
syslog.priority		= LOG_INFO
syslog.facility		= LOG_LOCAL2
clearenvironment	= no

# Allow Sudosh to execute -c arguments?  If so, what?
-c arg allow = *
```

**Comment by none-da** [comment]
I started using `ForwardAgent yes` approach only after realizing that with `ProxyCommand` all commands are exchanged over an encrypted tunnel and there is no way for sudosh2 to track the actions. Can anyone confirm if I am missing something here (with `ProxyCommand`) ?

**Comment by squash** [comment]
The behavior you are seeing is correct. Since you're using the -c arg feature, the commands sent along are executed instead of a shell. This is generally meant for allowing things like scp/sftp, but can also be used for other things. Sudosh will log that it happened but those commands are executed directly (if allowed) and their output can't be logged as such.

The straightforward solution would be to use sudosh on the server rather than/in addition to the bastion host.

**Comment by none-da** [comment]
Agreed. But I was able to achieve what I want by logging into the server machine in two steps. So instead of
```sh
ssh -A -t nanda@bastion ssh -v ubuntu@server
```
I do this now 👇
```sh
# From client/latop
ssh -A -t <username>@jumpbox-ip

# once logged-in to the jumpbox
ssh <username>@server-ip
```
And all the sessions are tracked as expected, including python REPL.
