### ISSUE TITLE
Issues with sudosh.conf

### ISSUE THREAD

**Issue by devnullsecurity** [squash/sudosh2#34]
We use sudosh in my Linux class to give us the opportunity to compile something.  We have been using it for years.  This semester we are having an issue with the config dir.  In all prior semesters we were able to simply run ./configure, make and sudo make install and have it work without issues.  It always set the conf dir to /etc.  This semester ./configure is setting the conf dir to /usr/local/etc, which is fine, but the program is then not finding the config file in /usr/local/etc when we try to run it.

[root@rbe0000-7 sudosh2]# sudosh
Warning: No config file found. Using compiled-in defaults:
Logdir  /var/log/sudosh
Default Shell:  /bin/sh
Syslog Disabled
Immutable Recordings Disabled

I was able to return to the old functional behavior by running ./configure --sysconfdir=/etc which set the config dir to /etc like it used to be and then doing make;make install and it worked as expected.

Let me know if you need any additional information.

**Comment by squash** [comment]
The result you get is correct, the previous behavior was non-standard. Your workaround is the correct method to get what you were looking for, although I appreciate that changing workflows can be painful.

**Comment by hugo-ricateau-tiime** [comment]
I think @devnullsecurity is right in the sens that as a bare `./configure && make` results in `config.h` containing `#define SYSCONFDIR "${prefix}/etc"` (note the non extension of the `prefix` variable). The result is a compiled binary that is looking for a config file at `${prefix}/etc/sudosh.conf` (which is obviously missing on most systems).

**Comment by squash** [comment]
Sorry for the delay but this is solved in [52a03c1](https://github.com/squash/sudosh2/commit/52a03c1442aa92669a933dbd9d687091de864a79)
