### ISSUE TITLE
sudosh.conf is not installed relative to $(DESTDIR)

### ISSUE THREAD

**Issue by jcbollinger** [squash/sudosh2#35]
When the distribution tarball is built and installed via
```
tar xzf sudosh2-1.0.7.tar.gz
cd sudosh2-1.0.7
./configure
make
make install DESTDIR=/staging/area
```
the build system attempts to install sudosh.conf at absolute path `/etc/sudosh.conf`, whereas it should attempt to install it at `/staging/area/etc/sudosh.conf` instead.  The custom installation code in `Makefile.am` looks like it ought to do the right thing, but the `Makefile.in` included in the package does not correspond.

Moreover, it ought to be possible to avoid a custom installation rule in the first place, which would be more robust and easier to maintain.

**Comment by jcbollinger** [comment]
Additionally, the custom installation rule for the config file should not attempt to set the owning user or group.  That is unnecessary when the installation is performed as a privileged user, and it doesn't work when the installation is performed as an ordinary user (to a directory under their control).

**Comment by squash** [comment]
The sudosh.conf target issue was fixed a while back and is in HEAD, I haven't made a versioned release since then.

Regarding the installation permissions those are the defaults for autoconf/automake but I'll look at the options there.

**Comment by jcbollinger** [comment]
Perhaps you have the DESTDIR changes in one of your repository clones, but they are *not* (all) in HEAD here on GH.  Again, the `src/Makefile.am` has the needed changes, but they are not reflected in `src/Makefile.in`.

As for the permissions, no, they are not defaults.  The custom installation recipe run `install` with options `-o 0 -g 0`, which is the problem.  That's custom code, and install recipes generated by Automake don't do that.

But the whole custom recipe thing seems to be doing things the hard way.  I would suggest this for (all of) `src/Makefile.am`:
```
bin_PROGRAMS=sudosh sudosh-replay
sudosh_SOURCES=sudosh.c rand.c parse.c string.c getopt.h  struct.h  super.h util.c
sudosh_replay_SOURCES=replay.c getopt.c getopt.h string.c parse.c  util.c

sysconf_DATA = sudosh.conf

EXTRA_DIST=sudosh.conf
```
Then you don't need to write `DESTDIR` support explicitly, nor explicitly manage file ownership or mode.

**Comment by squash** [comment]
I think I misunderstood your initial report, I'll look closer when I'm not on my phone.

**Comment by squash** [comment]
I believe @90f7649 will take care of your issue, can you please verify?

**Comment by jcbollinger** [comment]
It looks like that will resolve the issue.

However, when I try to build the project from the current head, I get:

> configure: error: cannot find required auxiliary files: compile

I suppose that arises from the upgrade to the latest Autotools having introduced a new support script to the project that is not yet tracked in Git.

**Comment by squash** [comment]
Good catch. I didn't notice the autotools version requirement got bumped as well. I've fixed that and added the compile script., if you wouldn't mind testing again 2e175e1

**Comment by jcbollinger** [comment]
The new head works for me.  I did have to work around an issue with the fact that git does not preserve file timestamps, but that's a separate problem, and not on you.

**Comment by squash** [comment]
Great, closing this bug, thanks!
