### ISSUE TITLE
Parsing IP addresses into the log script.

### ISSUE THREAD

**Issue by Abraham-Alfred** [squash/sudosh2#36]
Hi, I am working on a project for my university and using sudosh2 as a recorder for recording shell sessions.

Is it possible to have sudosh2 configured to record an IP address of the client when a login session happens and to have the recorded session's script have said IP address inside it?

**Comment by squash** [comment]
sudosh doesn't get that IP address directly as the connection is still all handled by ssh. It should be in the environment, would your need be met by adding an echo in /etc/profile ?

Example:
`if [ "${SSH_CLIENT}" ]; then
        echo "Client: " ${SSH_CLIENT}
fi
`

**Comment by Abraham-Alfred** [comment]
That would work in a normal usecase. However, it wont for mine unfortunately. 

What I'm trying to do is when the user logs into the sudosh shell, their IP address to be recorded upon login. 

I have a workaround which I will implement for this. Since the "last" command already records this information, I'm planning to parse this into a filtered file for a specific user being monitored by sudosh. This will be then run as a "systemd" service.
 
Thanks for your help anyway! :).
