### ISSUE TITLE
Error while compiling with running make command

### ISSUE THREAD

**Issue by aravindragu** [squash/sudosh2#37]
OS : Ubuntu
OS Version : 20.0.4
GCC installed 

Getting below error while running make command
 
make  all-recursive
make[1]: Entering directory '/root/sudosh'
Making all in src
make[2]: Entering directory '/root/sudosh/src'
gcc -DHAVE_CONFIG_H -I. -I..     -g -O2 -Werror -MT sudosh.o -MD -MP -MF .deps/sudosh.Tpo -c -o sudosh.o sudosh.c
sudosh.c: In function ‘main’:
sudosh.c:348:50: error: ‘/’ directive output may be truncated writing 1 byte into a region of size between 0 and 8191 [-Werror=format-truncation=]
  348 |   snprintf (script.name, (size_t) BUFSIZ - 1, "%s/%s%c%s%cscript%c%i%c%s",
      |                                                  ^
sudosh.c:348:47: note: using the range [-2147483648, 2147483647] for directive argument
  348 |   snprintf (script.name, (size_t) BUFSIZ - 1, "%s/%s%c%s%cscript%c%i%c%s",
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:867,
                 from super.h:30,
                 from sudosh.c:21:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output 13 or more bytes (assuming 24586) into a destination of size 8191
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sudosh.c:352:50: error: ‘/’ directive output may be truncated writing 1 byte into a region of size between 0 and 8191 [-Werror=format-truncation=]
  352 |   snprintf (timing.name, (size_t) BUFSIZ - 1, "%s/%s%c%s%ctime%c%i%c%s",
      |                                                  ^
sudosh.c:352:47: note: using the range [-2147483648, 2147483647] for directive argument
  352 |   snprintf (timing.name, (size_t) BUFSIZ - 1, "%s/%s%c%s%ctime%c%i%c%s",
      |                                               ^~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:867,
                 from super.h:30,
                 from sudosh.c:21:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output 11 or more bytes (assuming 24584) into a destination of size 8191
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sudosh.c:363:28: error: ‘%s’ directive output may be truncated writing up to 8191 bytes into a region of size 8170 [-Werror=format-truncation=]
  363 |      "starting session for %s as %s, tty %s, shell %s", user.from, user.to,
      |                            ^~                           ~~~~~~~~~
In file included from /usr/include/stdio.h:867,
                 from super.h:30,
                 from sudosh.c:21:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output 40 or more bytes (assuming 16422) into a destination of size 8191
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sudosh.c:623:52: error: ‘%s’ directive output may be truncated writing up to 8191 bytes into a region of size 8183 [-Werror=format-truncation=]
  623 |   snprintf (user.logname.str, BUFSIZ - 1, "LOGNAME=%s", user.to);
      |                                                    ^~   ~~~~~~~
In file included from /usr/include/stdio.h:867,
                 from super.h:30,
                 from sudosh.c:21:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output between 9 and 8200 bytes into a destination of size 8191
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
sudosh.c:206:11: error: ‘/’ directive output may be truncated writing 1 byte into a region of size between 0 and 8191 [-Werror=format-truncation=]
  206 |        "%s/%s%c%s%cinteractive%c%i%c%s",
      |           ^
sudosh.c:206:8: note: using the range [-2147483648, 2147483647] for directive argument
  206 |        "%s/%s%c%s%cinteractive%c%i%c%s",
      |        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/stdio.h:867,
                 from super.h:30,
                 from sudosh.c:21:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:67:10: note: ‘__builtin___snprintf_chk’ output 18 or more bytes (assuming 24591) into a destination of size 8191
   67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   68 |        __bos (__s), __fmt, __va_arg_pack ());
      |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:273: sudosh.o] Error 1
make[2]: Leaving directory '/root/sudosh/src'
make[1]: *** [Makefile:422: all-recursive] Error 1
make[1]: Leaving directory '/root/sudosh'
make: *** [Makefile:240: all] Error 2

**Comment by squash** [comment]
OK great!
