### ISSUE TITLE
Not able to execute command remotely post enabling sudosh

### ISSUE THREAD

**Issue by aravindragu** [squash/sudosh2#39]
Whitelisted few command in sudosh.conf file but while executing getting error 

]$ /usr/local/bin/ssh prod_monitor sh -c 'date && echo fine'
Output Error : 
"sh -c date && echo fine" isn't allowed to be executed with process or redirect controls.

Also let me know the command to replay the recordings . 

--
Aravindan R

**Comment by squash** [comment]
Please include the relevant lines from sudosh.conf, and also what version of sudosh you are using. Note that there are several fixes in git master since the last release.

**Comment by squash** [comment]
Closing ticket for lack of response
