### ISSUE TITLE
Broken Replay using instant output 0 + strange characters

### ISSUE THREAD

**Issue by refrain** [squash/sudosh2#4]
I have encountered some broken replays when using instant output 0, but it will work with >0, however it will print some weird numbers and characters during vim and at the end of the replay.  I'm running sudosh 1.0.6 on Centos 6.6.

Here is a link to my slightly broken replay:

http://refrain.duckdns.org/jchang-jchang-script-1432255414-zPf34BVy04o95J27
http://refrain.duckdns.org/jchang-jchang-time-1432255414-zPf34BVy04o95J27

Let me know if you need more info...

**Comment by squash** [comment]
Looks like tty control sequences, can you tel lme what shell you are running and the value of `echo $TERM`?

**Comment by refrain** [comment]
bash, xterm
