### ISSUE TITLE
1.0.7 -  sudosh.o -  error: infinite recursion detected

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [squash/sudosh2#43]
Using your spec file on Fedora with minor changes these errors come up in %build stage from RPM:

`
sudosh.c: In function 'bye':
sudosh.c:654:1: error: infinite recursion detected [-Werror=infinite-recursion]
  654 | bye (int signum)
      | ^~~
sudosh.c:663:7: note: recursive call
  663 |       bye (EXIT_FAILURE);
      |       ^~~~~~~~~~~~~~~~~~
sudosh.c:673:7: note: recursive call
  673 |       bye (EXIT_FAILURE);
      |       ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:393: sudosh.o] Error 1`

**Comment by Chewbakka-Wakka** [comment]
Also... 
%configure \                                                                                                                                                                                                                                                                                                                                                                     

Neither of these options seems to work?                                                                                                                                                                                         #       -D werror=false \                                                                                                                                                                                        #       --disable-werror \                          

With that, warnings shouldn't be treated as errors.

**Comment by Chewbakka-Wakka** [comment]
Again from HEAD:

tor-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -Werror -c -o sudosh.o sudosh.c
sudosh.c: In function ‘bye’:
sudosh.c:654:1: error: infinite recursion detected [-Werror=infinite-recursion]
  654 | bye (int signum)
      | ^~~
sudosh.c:663:7: note: recursive call
  663 |       bye (EXIT_FAILURE);
      |       ^~~~~~~~~~~~~~~~~~
sudosh.c:673:7: note: recursive call
  673 |       bye (EXIT_FAILURE);
      |       ^~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[2]: *** [Makefile:423: sudosh.o] Error 1

**Comment by squash** [comment]
fixed in HEAD
