### ISSUE TITLE
1.0.7 - replay.o replay.c - error: 'strncpy' output may be truncated copying

### ISSUE THREAD

**Issue by Chewbakka-Wakka** [squash/sudosh2#44]
On build stage in RPM from latest 1.0.7:

`-Werror -c -o replay.o replay.c
replay.c: In function 'main':
replay.c:226:15: error: 'strncpy' output may be truncated copying 8191 bytes from a string of length 8191 [-Werror=stringop-truncation]
  226 |               strncpy (s->from, from, BUFSIZ - 1);
      |               ^
replay.c:227:15: error: 'strncpy' output may be truncated copying 8191 bytes from a string of length 8191 [-Werror=stringop-truncation]
  227 |               strncpy (s->to, to, BUFSIZ - 1);
      |               ^
replay.c:228:15: error: 'strncpy' output may be truncated copying 8191 bytes from a string of length 8191 [-Werror=stringop-truncation]
  228 |               strncpy (s->type, type, BUFSIZ - 1);
      |               ^
replay.c:229:15: error: 'strncpy' output may be truncated copying 8191 bytes from a string of length 8191 [-Werror=stringop-truncation]
  229 |               strncpy (s->randstr, randstr, BUFSIZ - 1);
      |               ^
replay.c:255:11: error: 'strncpy' output may be truncated copying 8191 bytes from a string of length 8191 [-Werror=stringop-truncation]
  255 |           strncpy (s->from, from, BUFSIZ - 1);
      |           ^
replay.c:256:11: error: 'strncpy' output may be truncated copying 8191 bytes from a string of length 8191 [-Werror=stringop-truncation]
  256 |           strncpy (s->to, to, BUFSIZ - 1);
      |           ^
replay.c:257:11: error: 'strncpy' output may be truncated copying 8191 bytes from a string of length 8191 [-Werror=stringop-truncation]
  257 |           strncpy (s->type, type, BUFSIZ - 1);
      |           ^
replay.c:258:11: error: 'strncpy' output may be truncated copying 8191 bytes from a string of length 8191 [-Werror=stringop-truncation]
  258 |           strncpy (s->randstr, randstr, BUFSIZ - 1);
      |           ^
cc1: all warnings being treated as errors
make[2]: *** [Makefile:393: replay.o] Error 1`

**Comment by Chewbakka-Wakka** [comment]
Also noticed the name being sudosh2 but the rpm unpacks files just called sudosh.
Maybe a rename is in order...

**Comment by wltechblog** [comment]
Please try building from HEAD, I've tested vs centos 9.

**Comment by squash** [comment]
Please try to build from HEAD. Tested on Centos 9.

**Comment by Chewbakka-Wakka** [comment]
Might be okay now, but I cannot quite confirm as the build still fails per my issue 43

**Comment by squash** [comment]
Please confirm when you have a chance.

**Comment by Chewbakka-Wakka** [comment]
Working
