### ISSUE TITLE
sudosh2 prevents us to input Japanese language

### ISSUE THREAD

**Issue by akadoya** [squash/sudosh2#6]
Hello,
I'm trying to install sudosh2 as users' login shell in our ssh jump box for logging our system engineers' activities.
We've been looking for a solution like this, and everything looks really nice except one thing.
I found that we cannot input Japanese languages when using sudosh as a login shell.
Even if the end point servers are not using sudosh2, once I jump into sudosh2 jump box machine and hop to the end point, I cannot input Japanese.
(while I can input J words if I jump from non-sudosh2 servers to the same end point)

we're facing this issue in the environment below.
OS - CentOS6.4 and 6.6 64bit
sudosh.conf
```
# Sudosh Configuration File
logdir                  = /var/log/sudosh
default shell           = /bin/bash
# Do not use '-'. our short account contains it.
delimiter               = _
syslog.priority         = LOG_NOTICE
syslog.facility         = LOG_LOCAL2
clearenvironment        = yes

# Allow Sudosh to execute -c arguments?  If so, what?
-c arg allow = scp
-c arg allow = rsync
```

I guess double-byte inputs are not scoped into sudosh2's design originally, but if you could give me a clue or any workaround about the reason of this situation, that'd be super appreciated!

**Comment by akadoya** [comment]
this is solved by our developers

**Comment by squash** [comment]
I would love to get a patch for this if you can provide that fix.

**Comment by akadoya** [comment]
we've just simply removed ISTRIP flag. I have no idea what intention was there for this flag, but so far it works for us.

 ```
--- a/src/sudosh.c
+++ b/src/sudosh.c
@@ -671,7 +671,7 @@ rawmode (int ttyfd)
     }

   termnew.c_cc[VEOF] = 1;
-  termnew.c_iflag = BRKINT | ISTRIP | IXON | IXANY;
+  termnew.c_iflag = BRKINT | IXON | IXANY;
   termnew.c_oflag = 0;
   termnew.c_cflag = termorig.c_cflag;
   termnew.c_lflag &= ~ECHO;
```
