### ISSUE TITLE
issue in sudosh replay is not working

### ISSUE THREAD

**Issue by nehankaj23** [squash/sudosh2#8]
Hi,

While running sudosh-replay its giving below error.

[root@via sudosh]# sudosh-replay praveen.sah-praveen.sah-1436616657-YBurFNwG5T3SZkFL
[replay.c, line 630]: [error]: line 1033: invalid timing information (!= %f %i\n)

**Comment by nehankaj23** [comment]
Hi,

Can anyone help me out from this.

Regards,
Pankaj

**Comment by squash** [comment]
Can you please attach a sample file and provide details of your system?

**Comment by squash** [comment]
Closing issue, can't address without a sample.
